services:
  # Reverse Proxy - NGINX
  nginx:
    image: nginx:latest
    ports:
      - "${NGINX_PORT_HTTP}:80"
      - "${NGINX_PORT_HTTPS}:443"
    restart: unless-stopped
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ../nginx/conf.d:/etc/nginx/conf.d:ro
      - ../nginx/snippets:/etc/nginx/snippets:ro
    networks:
      - internal
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost/health"]
      interval: 10s
      timeout: 5s
      retries: 5

