services:
  # LLM Runtime - Ollama
  ollama:
    image: ollama/ollama:latest
    expose:
      - "11434"
    # ports:
    #  - "${OLLAMA_PORT}:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - internal
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "ollama list"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s
    # NVIDIA GPU support
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  # LLM Chat - Open WebUI
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    expose:
      - "8080"
    # ports:
    #   - "${OPEN_WEBUI_PORT}:8080"
    volumes:
      - open_webui_data:/app/backend/data
    networks:
      - internal
    restart: unless-stopped
    depends_on:
      postgres:
          condition: service_healthy
      ollama:
          condition: service_healthy
