services:
  # Database - Postgres
  postgres:
    image: pgvector/pgvector:pg18-trixie
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    expose:
      - "5432"
    # ports:
    #   - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - internal
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Database UI - pgAdmin
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
      - PGADMIN_CONFIG_ALLOW_SPECIAL_EMAIL_DOMAINS=["local"]
    expose:
      - "80"
      - "443"
    # ports:
    #   - "${PGADMIN_PORT_HTTP}:80"
    #   - "${PGADMIN_PORT_HTTPS}:443"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - internal
    restart: unless-stopped
    depends_on:
      - postgres
