services:
  # Metrics collection - Prometheus
  prometheus:
    image: prom/prometheus:latest
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    expose:
      - "9090"
    volumes:
      - ../prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    networks:
      - internal
    restart: unless-stopped

  # Monitoring Dashboard - Grafana
  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - GF_PLUGINS_PREINSTALL=grafana-clock-panel
      - GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s:/grafana
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    expose:
      - "3000"
    volumes:
      - ../grafana/provisioning:/etc/grafana/provisioning:ro
      - grafana_data:/var/lib/grafana
    networks:
      - internal
    restart: unless-stopped
    depends_on:
      - prometheus

  # Container metrics - cAdvisor
  # System metrics - Node Exporter
  # Db Metrics - Postgres Exporter
  # Log aggregation - Loki
  # Log collection - Alloy

